
openapi: 3.1.0
info:
  title: find dish
  version: 1.0.0
paths:
  '/dish/{id}':
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: the dish
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  ingredient:
                    type: array
                    items:
                      type: string
                example:
                  id: 1
                  name: Pizza
                  price: 12.5
                  ingredients:
                    - cheese
                    - tomato
                    - ham
  '/ingredient':
     get:
       parameters:
         - offest:
             in: path
             schema:
               type: integer
         - size:
             in: query
             schema:
               type: integer