openapi: 3.1.0
info:
  title: find dish
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  '/ingredient':
    description: retourne tous les ingrédients
    get:
      responses:
        '200':
          description: succès de la requête
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientEntity'

  '/ingredient/{id}':
    description: retourne l'ingrédient correspondant à l'id
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: succès de la requête
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientEntity'

  '/ingredients/{id}/stock':
    get:
      summary: retourne la valeur du stock d'un ingrédient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: at
          in: query
          required: true
          schema:
            type: string
            format: date-time
            example: "2026-01-02T12:00:00Z"
        - name: unit
          in: query
          required: true
          description: Unité du stock à récupérer
          schema:
            type: string
      responses:
        '200':
          description: succès de la requête
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockValues'

components:
  schemas:
    IngredientEntity:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: float
        category:
          type: string
          enum:
            - ANIMAL
            - VEGETABLE
            - DAIRY
            - OTHER
      example:
        id: 1
        name: Pizza
        price: 12.5
        category: ANIMAL

    DishEntity:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: float
        dish_type:
          type: string
          enum:
            - DESSERT
            - STARTER
            - MAIN
      example:
        id: 3
        name: Lasagne
        price: 15.75
        dish_type: MAIN

    StockValues:
      type: object
      properties:
        quantity:
          type: integer
        unit:
          type: string
          enum:
            - KG
            - PCS
            - L
      example:
        quantity: 25
        unit: KG